### ISSUE TITLE
Open source email system

### ISSUE THREAD

**Issue by zzmarkzz321** [HackMerced/HackMerced-III#3]
- [ ] Get Familiar with the code base
- [ ] Look into the open source libraries for emailing (example: mailgun API)
- [ ] Design the service 
- [ ] Get approval from PM
- [ ] Implement the service
- [ ] Get approval from PM
- [ ] Merge into master

**Comment by vaibhavchellani** [comment]
is anyone working on this ?
@4shub @sorariku20 @Artsyy @ronniepanaligan

**Comment by vaibhavchellani** [comment]
please let me know if i can work on this , if anyone isnt

**Comment by zzmarkzz321** [comment]
Hey @vaibhavchellani !
The specifications for this task has changed. We still need to be able to send emails to users, so If you are interested in working on this I can go ahead and tag you in an updated issue.

**Comment by zzmarkzz321** [comment]
Moved to https://github.com/HackMerced/HackMerced/issues/19
